version: "3.3"
services:
  web:
    image: node-test:0.1
    deploy:
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
    volumes:
      - ./:/app
    ports:
      - "3000:3000"
    links:
      - mongo
  mongo:
    image: mongo
    deploy:
      resources:
        limits:
          cpus: "0.2"
          memory: 100M
    ports:
      - "27017:27017"
    volumes:
      - /data/dbc