version: "3"
services:
  web:
    build: .
    deploy:
      replicas: 2
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure
    ports:
      - "5000:5000"
    networks:
      - webnet
    links:
      - mongo
  mongo:
    image: mongo
    deploy:
      resources:
        limits:
          cpus: "0.2"
          memory: 100M
    ports:
      - "27017:27017"
    volumes:
      - /data/dbc
    networks:
      - webnet
networks:
  webnet: